### PR TITLE
Use scene.skyBox instead of copy of default starmap.

### PR DESCRIPTION
**Pull request by emackey**
/cc @moneimne @lilleyse

### CODE REVIEW

**Comment by emackey** [comment]
This is a PR into AnalyticalGraphicsInc/cesium#5641.

**Comment by lilleyse** [comment]
@moneimne can you merge? I think this may be the last thing for the pull request.

**Comment by emackey** [comment]
I added some fixes for the smart quotes and other characters in LICENSE.md.

**Comment by lilleyse** [comment]
@emackey I cherry-picked your commits into #5641

**Pull request closed without merging**
